language: python
python:
  - "2.7"
install: make install
script:
  - make test_hermes
  - make more_tests
notifications:
  email:
    recipients:
      - yi.t.xu@mail.mcgill.ca
  on_success: never
  on_failure: always